name = "Wooden Sword"
type = "Weapon - One Handed"
sprite_tileset = "materials2.tsx"
sprite_name = "wooden_sword"
stackable = false
item_type = "Weapon"

# Extra designer fields (optional):
# attack = 6
# value = 8
# weight = 1
